### ISSUE TITLE
ScriptHawk fails to open and throws a fatal exception in BizHawk

### ISSUE THREAD

**Issue by clanker-ii** [Isotarge/ScriptHawk#7]
Steps to reproduce the result: run BT(USA), Lua -> Open -> ScriptHawk.lua
Specs: Windows 10 

BizHawk error:
 

> System.NullReferenceException: Object reference not set to an instance of an object.
>    at BizHawk.Client.EmuHawk.LuaConsole.ResumeScripts(Boolean includeFrameWaiters)
>    at BizHawk.Client.EmuHawk.MainForm.ProgramRunLoop()
>    at BizHawk.Client.EmuHawk.Program.SubMain(String[] args)

**Comment by clanker-ii** [comment]
disregard this, need to run preinstaller + im reinstalling bizhawk
